spring.application.name=auth-service
server.port=8084

spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.access.expiration-time=${ACCESS_EXPIRATION_TIME}
jwt.refresh.expiration-time=${REFRESH_EXPIRATION_TIME}

auth-service.public-paths=/api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/refresh
auth-service.check-endpoint=/api/v1/auth/internal/token/validate

cors.allowed-origins=${ALLOWED_ORIGINS}
cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
cors.allowed-headers=Content-Type,Authorization,X-Requested-With
