version: "3.8"

services:
  gateway:
    build:
      context: ./api-gateway-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${{ secrets.DOCKER_USERNAME }}/api-gateway-service:${TAG}
    ports:
      - "8888:8888"
    env_file:
      - .env.services.prod
    depends_on:
      - auth-service
      - points-service
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${{ secrets.DOCKER_USERNAME }}/auth-service:${TAG}
    env_file:
      - .env.services.prod
    networks:
      - backend

  points-service:
    build:
      context: ./points-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${{ secrets.DOCKER_USERNAME }}/points-service:${TAG}
    env_file:
      - .env.services.prod
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${{ secrets.DOCKER_USERNAME }}/notification-service:${TAG}
    env_file:
      - .env.services.prod
    networks:
      - backend

networks:
  backend:
    external: true
