version: "3.8"

services:
  gateway:
    build:
      context: ./api-gateway-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${DOCKER_USERNAME}/api-gateway-service:${IMAGE_TAG}
    ports:
      - "8888:8888"      

    depends_on:
      - auth-service
      - points-service
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${DOCKER_USERNAME}/auth-service:${IMAGE_TAG}
    networks:
      - backend

  points-service:
    build:
      context: ./points-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${DOCKER_USERNAME}/points-service:${IMAGE_TAG}
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ${DOCKER_USERNAME}/notification-service:${IMAGE_TAG}
    networks:
      - backend

networks:
  backend:
    external: true
