server:
  port: 8888

spring:
  application:
    name: api-gateway-service
  kafka:
    consumer:
      group-id: api-gateway-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: itmo.programming.*
            use:
              type:
                headers: false
    bootstrap-servers: ${KAFKA_URL}
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: points-service
            uri: ${POINTS_SERVICE_URL}
            predicates:
              - Path=/api/v1/point/**
          - id: auth-service
            uri: ${AUTH_SERVICE_URL}
            predicates:
              - Path=/api/v1/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: ${JWT_SECRET}

auth-service:
  url: ${AUTH_SERVICE_URL}
  public-paths: /api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/refresh
  check-endpoint: /api/v1/auth/internal/token/validate

cors:
  allowed-origins: ${ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: Content-Type,Authorization,X-Requested-With
