name: backend deploy
on:
  push:
    branches: [master]
  pull-request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Java environment
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-microservices-jars
          path: |
            **/build/libs/*.jar
            !**/build/libs/*-plain.jar
          if-no-files-found: error
          retention-days: 30
