name: backend deploy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello user! it is test"
      - run: echo "my repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "code was clonned to the runner"
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "job status is ${{ job.status }}"